#!/bin/bash -v

LOCALDIR=/usr/local/superlumic/scripts
LOCALBIN=/usr/local/bin
REPOURL=https://raw.githubusercontent.com/FlyingBinary/superlumic/fbmaster/scripts

function getScript {
    sudo curl -s $REPOURL/$1 > $LOCALDIR/$1
    sudo chmod 755 $LOCALDIR/$1
    # For convenience of standalone invocation, symlink into /usr/local/bin
    # TODO: Ensure that path references /user/loca/bin
    sudo ln -s $LOCALDIR/$1 /usr/local/$1
}

sudo mkdir -p $LOCALDIR
sudo mkdir -p $LOCALBIN
getScript adminuser
getScript createadministrator
getScript checkuser
