#!/bin/bash -v

HOMEHELPDIR=~/.superlumic
REPOURL=https://raw.githubusercontent.com/FlyingBinary/superlumic/fbmaster/helpers
USER=spud


function getHelper {
    sudo curl -s $REPOURL/$1 > $HOMEHELPDIR/$1
    sudo chmod 755 $HOMEHELPDIR/$1
}

mkdir -p $HOMEHELPDIR


if [[ -p /dev/stdin ]]; then
    echo "Stdin is coming from a pipe"
    echo "Switch to terminal"
    getHelper su-1
    # Drain the pipe
    pipeByte=$(dd bs=1 count=1 2>/dev/null | od -t o1 -A n)
    while [ -z "$pipeByte" ]; do
        echo -n "$pipeByte"
        pipeByte=$(dd bs=1 count=1 2>/dev/null | od -t o1 -A n)
    done
    ~/.superlumic/su-1
    exit $?
fi
if [[ -t 0 ]]; then
    echo "Stdin is coming from the terminal"
    getHelper getscripts
    echo "User is '$USER'"
    su "$USER" -c "~/.superlumic/getscripts"
    ~/.superlumic/su-2
    exit $?
fi
if [[ ! -t 0 && ! -p /dev/stdin ]]
then
    echo "stdin is redirected"
fi
echo -n "Enter some text to exit: "
read
echo "$REPLY"