#!/bin/bash -v

# This is a helper script for Superlumic macOS configuration
# The only purpose of this script is to allow us to run getscripts as administrator user
# It may be safely deleted - it will be re-downloaded when needed
if [ -z $1 ]; then
    echo "Please provide an admin user name" >&2
    exit 63
fi

echo "User is $1"
su "$1" -c "~/.superlumic/getscripts"