#!/bin/bash
#    echo "(debug) starting ${0##*/}"

if [ "${0##*/}" == "checkuserq" ]; then quiet=true; else quiet=false; fi
#    echo "(debug) quiet=$quiet"

function printMessage {
    if ! "$quiet"; then
        out=$2
        if [ -z $out ]; then
            out=1
        fi
        if [ $out == 1 ]; then
            echo $1 >&1
        else
            echo $1 >&2
        fi
        return 0
    else
        return 1
    fi
}

if [ "$1" != "exists" ] && [ "$1" != "member" ]; then
    printMessage "Usage: ${0##*/} exists username|member username group" 2
    printMessage "       exists - check user exists" 2
    printMessage "       member - check if user is a member of group" 2
    exit 64
fi

if [ -z $2 ]; then
    printMessage "Please provide a user name" 2
    exit 65
fi
#    echo "(debug) user name='$2'"

guid=
if dscl . -read /Users/$2 UniqueID >/dev/null 2>&1
then
    guid=$(dscl . -read /Users/$2 GeneratedUID | cut -f 2 -d ' ')
fi
#    echo "(debug) guid='$guid'"

if [ "$1" == "exists" ]; then
#    echo "(debug) checking existence"
    if [ ! -z "$guid" ]; then
        printMessage "YES: Found user '$2'"
        exit 0
    else
        printMessage "NO: Could not find user '$2'"
        exit 1
    fi
fi

if [ "$1" == "member" ]; then
#    echo "(debug) checking membership"
    if [ -z "$guid" ]; then
        printMessage "Could not find user '$2' - exiting" 2
        exit 66
    fi
    if [ -z $3 ]; then
        printMessage "Please provide a group name" 2
        exit 67
    fi
#    echo "(debug) group name='$3'"
    dscl . -read /Groups/$3 GroupMembers >/dev/null 2>&1
    status=$?
#    echo "(debug) read status='$status'"
    if [ $status == 56 ]; then
        printMessage "Could not find group '$3' - exiting" 2
        exit 68
    fi
    member=$(dscl . -read /Groups/$3 GroupMembers | grep "$guid")
#    echo "(debug) member result='$member'"
    membership=$(dscl . -read /Groups/$3 GroupMembership | grep "$2")
#    echo "(debug) membership result='$membership'"
    if [ ! -z "$member" ] || [ ! -z "$membership" ]; then
        printMessage "YES: Found user '$2' in group '$3'"
        exit 0
    else
        printMessage "NO: Could not find user '$2' in group '$3'"
        exit 1
    fi
fi
